### ISSUE TITLE
Very nice

### ISSUE THREAD

**Issue by bunnybuddy213** [YimMenu-Lua/SAMURAI-Scenarios#2]
very nice animations, and for sure it will be better with time !

**Comment by xesdoog** [comment]
> very nice animations, and for sure it will be better with time !

Thank you for your feedback ♥
Upcoming changes for **scenarios** will be a more user-friendly display list but if you're interested in **animations**, check out [SAMURAI-Animations](https://github.com/YimMenu-Lua/SAMURAI-s-Animations).
